### PR TITLE
Translations of python-docs-zh-tw

### PR DESCRIPTION
**Pull request by StevenHsuYL**
tutorial/interpreter.po
tutorial/introduction.po
Could you update the zh-tw pages with these translation files?
If you could help updating the zh-tw pages, I will continue the translation for zh-tw readers.
Thanks a lot!

### CODE REVIEW

**Comment by zhsj** [comment]
Hi,

zh-tw translations should be sent to https://github.com/python/python-docs-zh-tw

I see you have created https://github.com/python/python-docs-zh-tw/pull/67 already. It looks like you didn't receive response, maybe you can try to contact the coordinator through telegram(t.me/PyDocTW)?

**Comment by StevenHsuYL** [comment]
Hi,
Thanks for the rapid response.
I had tried to find the coordinator in telegram, but he was not there.
Therefore, there is no other way to refresh the zh-tw translation. 
Could you help us for this?

I came here because I found that the pages in zh-tw tutorial used zh-cn translation in most paragraph.
If you could help us to refresh the zh-tw pages, it would be a great favor for Taiwanese readers.

Thanks again!

**Comment by zhsj** [comment]
I think you can reach the community at doc-sig@python.org mailinglist. Basically if the previous coordinator is busy, then someone needs to become a new coordinator. The he will be added as maintainer for python-docs-zh-tw repository.

The doc build script only fetchs translations of zh-tw from python-docs-zh-tw repository.

**Comment by zhsj** [comment]
And it seems @adrianliaw is still around, maybe you can try more ways to contact him? like twitter https://twitter.com/adrianliaw2000

**Comment by StevenHsuYL** [comment]
I should try harder to connect him.
Thanks again for the information, anyway!

**Comment by adrianliaw** [comment]
@zhsj Thank you for the explanation and the pointers!  Yes, I'm still around, I'm just in a different time zone, and like you said, pretty busy at the moment.

**Pull request closed without merging**
